"""migration

Revision ID: a73cda4d3657
Revises: b9689f66586b
Create Date: 2022-05-18 16:56:51.949477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a73cda4d3657'
down_revision = 'b9689f66586b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'complete')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('complete', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
