"""migration

Revision ID: b9689f66586b
Revises: b9a3d81c86c8
Create Date: 2022-05-18 16:56:31.299219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9689f66586b'
down_revision = 'b9a3d81c86c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('complete', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'complete')
    # ### end Alembic commands ###
